### ISSUE TITLE
Recycler ViewHolder usability

### ISSUE THREAD

**Issue by DATL4G** [kirich1409/ViewBindingPropertyDelegate#22]
Is this usable in a RecyclerView ViewHolder?

If so, the README should be expanded since it only contains usability in activities, fragments and dialogs.
If not that would be a nice feature.

**Comment by kirich1409** [comment]
The library don’t have example with `RecyclerView.ViewHolder` because it doesn’t need. The main purpose of the library - connect `ViewBinding` with `Lifecycle` and prevent memory leaks. It isn’t the first time when I heard the question. Need to cover that or add support for `RecycelrView.ViewHolder`.

**Comment by kirich1409** [comment]
The lazy binder will be added in 1.4.0

**Comment by kirich1409** [comment]
See #27
